apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
  labels:
    app: ping-pong-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-api
  template:
    metadata:
      labels:
        app: ping-pong-api
    spec:
      containers:
      - name: ping-pong-api-container
        image: ping_pong_game:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-api-service
spec:
  type: NodePort
  ports:
  - targetPort: 5000
    port: 5000
    nodePort: 31300
  selector: 
    app: ping-pong-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping-pong-ingress
spec:
  rules:
  - host: getpingpong.com  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ping-pong-api
            port:
              number: 5000
